### ISSUE TITLE
Loading browser fails

### ISSUE THREAD

**Issue by rduinmayer** [restagner/cucumber-groovy-selenium#2]
Hi restagner,

Do you have any idea why the browser does not load?

I downloaded the source, i did mvn clean verify after that the test run but no browser is started.

Any tips?

@restagner @aslakhellesoy @poojaoza

**Comment by rduinmayer** [comment]
Oke i found a "switch" So now the driver is Firefox. 
```
    private WebDriver loadSelenium() {
        driver = new EventFiringWebDriver(new FirefoxDriver()).register(new MyWebDriverEventListener())
//        driver = new EventFiringWebDriver(new HtmlUnitDriver(true)).register(new MyWebDriverEventListener())
        return driver
```

But when i run the tests, firefox starts but the tests are not being run in the browser at all.  Now i get the following in the logs:

> org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

Any ideas? @restagner @aslakhellesoy @poojaoza

**Comment by rduinmayer** [comment]
![conemu64_2016-08-10_16-32-50](https://cloud.githubusercontent.com/assets/1469666/17558680/b69057c2-5f1b-11e6-940d-42b5b0c533d2.png)

**Comment by restagner** [comment]
@rduinmayer 

From your last post, it seems you were able to figure out the issue.  Based on the previous posts, I suspect that the version of Selenium defined within pom file is quite old (2.47.1), and that the version of Firefox you are attempting to connect to is the latest version.  This mismatch likely leads to the error you noted earlier

```text
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
```

To resolve this issue, update the version of Selenium within the pom file.

**Comment by rduinmayer** [comment]
Thanks for the reply @restagner 

I updated the version just now and still the same problem :(

        <selenium.version>2.53.1</selenium.version>

I did mvn install. tthat should be engouh right to update the pom?

**Comment by restagner** [comment]
@rduinmayer 

Which version of Firefox are you using?

**Comment by rduinmayer** [comment]
@restagner i tried downgrading (to fix the earlier problem) so i am on version 45.1.0 or Fixefox right now. I tried a few versions between that and the latest version.

**Comment by restagner** [comment]
Based on the Selenium changelog (https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG), it appears that FF45 should work.  I'll give it a try on my end

**Comment by restagner** [comment]
@rduinmayer

**Comment by restagner** [comment]
@rduinmayer 

I upgraded my local copy of Selenium to 2.53.1.  After updating the pom file, I was forced to update the `MyWebDriverEventListener` class.  Apparently, with version 2.53.1, the API surrounding the `WebDriverEventListener` has changed.  

I have committed my changes back to the repository.  You may want to perform a *git pull* to obtain the latest changes

With that being said, I was able to run the tests using FF 44.0.1 and FF 38.

**Comment by rduinmayer** [comment]
Awesome, latst version of FF and version of selenium 2.53.1 work like a charm. There are some things functional not correct in the test but it opens google and searches something so this is fine.

Thanks for updating the project :) :+1:  @restagner
